izj_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: IZJUserBundle:Default:index }

izj_user_index:
    path:     /user/index
    defaults: {_controller: IZJUserBundle:User:index}

izj_user_add:
    path:     /user/add
    defaults: {_controller: IZJUserBundle:User:add}

izj_user_edit:
    path:     /user/edit/{id}
    defaults: {_controller: IZJUserBundle:User:edit}

izj_user_view:
    path:     /user/view/{id}
    defaults: {_controller: IZJUserBundle:User:view}

izj_user_delete:
    path:     /user/delete/{id}
    defaults: {_controller: IZJUserBundle:User:delete}        